---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

fail_fast: true
default_stages:
 - commit
 - push

repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v3.4.0
   hooks:
    - id: mixed-line-ending
      args:
       - '--fix=no'
    - id: check-yaml
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-vcs-permalinks
    - id: forbid-new-submodules

 - repo: https://github.com/jorisroovers/gitlint
   rev: v0.15.0
   hooks:
    - id: gitlint
