---
# yamllint disable rule:comments-indentation

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

fail_fast: true
default_stages:
 - commit
 - push

repos:

 # common stuff
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v3.4.0
   hooks:
    - id: mixed-line-ending
      args:
       - '--fix=no'
    - id: check-yaml
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-vcs-permalinks
    - id: forbid-new-submodules

 # commit messages (IMPORTANT: install it with: `pre-commit install --hook-type commit-msg`)
 - repo: https://github.com/jorisroovers/gitlint
   rev: v0.15.0
   hooks:
    - id: gitlint
      stages:
       - commit-msg

# # shellcheck
# - repo: git://github.com/detailyang/pre-commit-shell
#   rev: 1.0.5
#   hooks:
#    - id: shell-lint
#      args:
#       - '--format=json'

 # replace help in USAGE of the README
 - repo: git://github.com/mbideau/pre-commit-makefile
   rev: v0.3.0
   hooks:
    - id: makefile-doc

 # shellcheck and markdown mostly
 - repo: https://github.com/jumanjihouse/pre-commit-hooks
   rev: 2.1.4
   hooks:
    - id: shellcheck
    - id: markdownlint
    # - id: require-ascii
    # - id: script-must-have-extension
    # - id: script-must-not-have-extension

 # 'make all' before push
 - repo: git://github.com/primeroz/pre-commit-hook-makefile-task
   rev: v0.0.2
   hooks:
    - id: makefile-task
      args:
       - 'all'
      stages:
       - push
